import Header from "@/components/Header";
import { Metadata } from "next";

const HomePage = () => {
  return <Header label="Home" />;
};

export default HomePage;

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};
