import { Metadata } from 'next'
import React from 'react'

const AboutPage = () => {
  return (
    <div>AboutPage</div>
  )
}

export default AboutPage


export const metadata: Metadata = {
    title: "About",
    description: "Generated by create next app",
}