import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UILayout from "@/components/UILayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Default title",
    template: "%s / X",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UILayout>{children}</UILayout>
      </body>
    </html>
  );
}
