import Header from "@/components/Header";
import { Metadata } from "next";

export default function Home() {
  return (
    <>
      <Header label="Home" />
    </>
  );
}

export const metadata: Metadata = {
  title: "Home / X",
  description: "Generated by create next app",
};
