import { Metadata } from "next";
import { FaXTwitter } from "react-icons/fa6";
import HomeSignup from "./HomeSignup";
import HomeLogin from "./HomeLogin";

export default function Home() {
  return (
    <>
      <div className="flex items-center p-10">
        <FaXTwitter
          color="white"
          size={400}
          className="lg:block hidden lg:w-[49%] "
        />
        <div className="lg:w-[49%]">
          <FaXTwitter color="white" size={50} className="lg:hidden block" />
          <h1 className="text-4xl mt-16 font-bold text-white">Happening now</h1>
          <h3 className="text-2xl mt-12 font-bold text-white">Join Today.</h3>
          <HomeSignup />
          <HomeLogin />
        </div>
      </div>
      {/* TODO FOOTER */}
    </>
  );
}

export const metadata: Metadata = {
  title: "X. It's what's happening / X",
  description: "Generated by create next app",
};
