import { Metadata } from "next";
import { FaApple, FaXTwitter } from "react-icons/fa6";
import { FcGoogle } from "react-icons/fc";

export default function Home() {
  return (
    <>
      <div className="flex items-center p-10">
        <FaXTwitter
          color="white"
          size={400}
          className="lg:block hidden lg:w-[49%] "
        />
        <div className="lg:w-[49%]">
          <FaXTwitter color="white" size={50} className="lg:hidden block" />
          <h1 className="text-4xl mt-16 font-bold text-white">Happening now</h1>
          <h3 className="text-2xl mt-12 font-bold text-white">Join Today.</h3>
          <div className=" flex flex-col gap-5 mt-5 w-[75%] md:w-[50%] lg:w-[50%] xl:w-[40%] 2xl:w-[20%] border-b-2 border-neutral-700 pb-4">
            <div className="bg-white flex px-5 py-2 rounded-full items-center justify-center hover:bg-opacity-90 transition cursor-pointer">
              <FcGoogle size={24} className="mr-2" />
              <p>Sign up with Google</p>
            </div>
            <div className="bg-white flex px-5 py-2 rounded-full items-center justify-center hover:bg-opacity-90 transition cursor-pointer">
              <FaApple size={24} className="mr-2" />
              <p>Sign up with Apple</p>
            </div>
          </div>
          <div className="bg-sky-500 text-white px-5 py-2 rounded-full mt-5 w-[75%] md:w-[50%] lg:w-[50%] xl:w-[40%] 2xl:w-[20%] text-center font-bold cursor-pointer">
            <p>Create Account</p>
          </div>
          <div className="w-[75%] md:w-[50%] lg:w-[50%] xl:w-[40%] 2xl:w-[20%]">
            <p className="text-zinc-500 text-xs mt-2">
              By signing up, you agree to the Terms of Service and Privacy
              Policy, including Cookie Use.
            </p>
          </div>
          <div className="mt-20">
            <h2 className="text-white text-xl font-bold">
              Already have an account?
            </h2>
            <div className="bg-black text-white px-5 py-2 rounded-full text-center border-[0.5px] border-sky-700 hover:bg-sky-500 hover:bg-opacity-10 transition cursor-pointer mt-4 w-[75%] md:w-[50%] lg:w-[40%] xl:w-[30%] 2xl:w-[20%]">
              <p>Sign in</p>
            </div>
          </div>
        </div>
      </div>
      {/* TODO FOOTER */}
    </>
  );
}

export const metadata: Metadata = {
  title: "X. It's what's happening / X",
  description: "Generated by create next app",
};
